- name: Undeploy MySQL service
  command: kubectl delete --ignore-not-found -f -
  args:
    stdin: "{{ lookup('template', 'mysql_deployment.yaml.j2') }}"
  register: undeploy_mysql_result
  changed_when: >-
    undeploy_mysql_result.stdout_lines
      | select('match', '^.* deleted$') | list | length > 0

- name: Wait for MySQL service to undeploy
  import_tasks: wait_for_undeploy.yaml

- name: Cleanup remaining MySQL resources
  command: kubectl delete --ignore-not-found -f -
  args:
    stdin: "{{ lookup('template', item + '.yaml.j2') }}"
  register: cleanup_mysql_result
  changed_when: >-
    cleanup_mysql_result.stdout_lines
      | select('match', '^.* deleted$') | list | length > 0
  loop:
  - mysql_svc
  - mysql_pvc
  - mysql_secret
