- name: Wait for MySQL service to roll out
  command: kubectl rollout status deploy -w=false {{ mysql_name | quote }}
  register: mysql_rollout_status
  changed_when: no
  until: >-
    mysql_rollout_status.stdout | regex_search('successfully rolled out')
    or mysql_rollout_status.stderr | regex_search('not found')
  retries: 60
  delay: 5
