

- name: Create sentinal resources
  command: kubectl apply -f -
  args:
    stdin: "{{ lookup('template', item + '.yaml.j2') }}"
  register: deploy_sentinal_svc_results
  changed_when: >-
    deploy_sentinal_svc_results.stdout_lines
      | reject('match', '^.* unchanged$') | list | length > 0
  loop:
  - sentinal_pvc
  - sentinals_deployment
  - sentinal_svc
  notify:
  - Wait for Wordpress service to roll out
  - Wait for Wordpress service to listen on external address
