- name: Undeploy Wordpress service
  command: kubectl delete --ignore-not-found -f -
  args:
    stdin: "{{ lookup('template', 'wordpress_deployment.yaml.j2') }}"
  register: undeploy_wordpress_result
  changed_when: >-
    undeploy_wordpress_result.stdout_lines
      | select('match', '^.* deleted$') | list | length > 0

- name: Wait for Wordpress service to undeploy
  import_tasks: wait_for_undeploy.yaml

- name: Delete remaining Wordpress resources
  command: kubectl delete --ignore-not-found -f -
  args:
    stdin: "{{ lookup('template', item + '.yaml.j2') }}"
  register: cleanup_wordpress_result
  changed_when: >-
    cleanup_wordpress_result.stdout_lines
      | select('match', '^.* deleted$') | list | length > 0
  loop:
  - wordpress_svc
  - wordpress_pvc

- name: Undeploy Wordpress database
  import_role:
    name: mysql
    tasks_from: undeploy
  vars:
    mysql_name: "{{ wordpress_db_name }}"
  when: wordpress_deploy_db|bool
  tags:
  - wordpress_db
