- name: Wait for Wordpress service to roll out
  command: kubectl rollout status deploy -w=false {{ wordpress_name | quote }}
  register: wordpress_rollout_status
  changed_when: no
  until: >-
    wordpress_rollout_status.stdout | regex_search('successfully rolled out')
    or wordpress_rollout_status.stderr | regex_search('not found')
  retries: 60
  delay: 5
